#  Install MongoDB Manual Steps.
#  Ref URL: https://docs.mongodb.com/manual/tutorial/install-mongodb-on-red-hat/
#
#    Setup MongoDB repos.
#    # curl -s -o /etc/yum.repos.d/mongodb.repo https://raw.githubusercontent.com/roboshop-devops-project/mongodb/main/mongo.repo
#    Install Mongo & Start Service.
#    # yum install -y mongodb-org
#    # systemctl enable mongod
#    # systemctl start mongod
#    Update Liste IP address from 127.0.0.1 to 0.0.0.0 in config file
#  Config file: /etc/mongod.conf
#
#    then restart the service
#
#    # systemctl restart mongod
#    Every Database needs the schema to be loaded for the application to work.
#    Download the schema and load it.
#
#    # curl -s -L -o /tmp/mongodb.zip "https://github.com/roboshop-devops-project/mongodb/archive/main.zip"
#
#    # cd /tmp
#    # unzip mongodb.zip
#    # cd mongodb-main
#    # mongo < catalogue.js
#    # mongo < users.js
#
#    Symbol < will take the input from a file and give that input to the command.

- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update mongodb config file to list to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongodb.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB service
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: yes

- name: Download MongoDB schema files
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Load catalogue schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/catalogue.js"
    idempotent: yes

- name: Load scheme user
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes

