#  The frontend is the service in RobotShop to serve the web content over Nginx.
#
#    To Install Nginx.
#
#    # yum install nginx -y
#    # systemctl enable nginx
#    # systemctl start nginx
#    Let's download the HTML content that serves the RoboSHop Project UI and deploy under the Nginx path.
#
#    # curl -s -L -o /tmp/frontend.zip "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
#    Deploy in Nginx Default Location.
#
#    # cd /usr/share/nginx/html
#    # rm -rf *
#    # unzip /tmp/frontend.zip
#    # mv frontend-main/* .
#    # mv static/* .
#    # rm -rf frontend-master static README.md
#    # mv localhost.conf /etc/nginx/default.d/roboshop.conf
#    Finally restart the service once to effect the changes.
#
#  # systemctl restart nginx



- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Download frontend schema files
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Remove old html web page
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent


- name: Copy the HTML files
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Reverse proxy configuration
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

#- name: Enable service NGINX, and not touch the state
#  ansible.builtin.service:
#    name: nginx
#    enabled: yes

- name: Start Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

