- name: Add application user
  ansible.builtin.user:
    name: roboshop
  register: app_user

- name: Download and unzip the {{COMPONENT}} content
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Remove old App content
  ansible.builtin.file:
    path: /usr/roboshop/{{COMPONENT}}
    state: absent


- name: Copy the HTML files
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop
