#Dispatch is the service which dispatches the product after purchase. It is written in GoLang, So wanted to install GoLang.
#
#Install GoLang
#  # yum install golang -y
#Add roboshop User
#  # useradd roboshop
#Switch to roboshop user and perform the following commands.
#$ curl -L -s -o /tmp/dispatch.zip https://github.com/roboshop-devops-project/dispatch/archive/refs/heads/main.zip
#$ unzip /tmp/dispatch.zip
#$ mv dispatch-main dispatch
#$ cd dispatch
#$ go mod init dispatch
#$ go get
#$ go build
#Update the systemd file and configure the systemd service
## mv /home/roboshop/dispatch/systemd.service /etc/systemd/system/dispatch.service
## systemctl daemon-reload
## systemctl enable dispatch
## systemctl start dispatch


- name: Install Golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Application user setup and Download app files
  import_tasks: app_user_setup.yml

- name: Install App dependencies
  ansible.builtin.shell: go mod init {{COMPONENT}} && go get && go build
  args:
    chdir: //home/roboshop/{{COMPONENT}}


- name: Application user setup and download app files
  import_tasks: systemd.yml

